services:
  katana-tester:
    build: .
    container_name: katana-tester
    volumes:
      - .:/home/pi/KATANA_INSTALLER
    privileged: true
    tty: true
    stdin_open: true
    command: /bin/bash
